[package]
name = "advent-of-code-2022-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array2d = "0.3.0"
rand = "0.8.3"
termion = "2.0.1"
